apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodcatalogueapp
  labels:
    app: foodcatalogueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcatalogueapp
  template:
    metadata:
      labels:
        app: foodcatalogueapp
    spec:
      containers:
        - name: foodcatalogueapp
          image: govindrana/foodcatalogue:15
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            # --- existing datasource vars ---
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: foodcataloguedb_url

---
apiVersion: v1
kind: Service
metadata:
  name: foodcatalogue-service
spec:
  selector:
    app: foodcatalogueapp
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
